### ISSUE TITLE
Guide view: Reload guide after performing edit

### ISSUE THREAD

**Issue by marczych** [iFixit/iFixitAndroid#138]
1) View a guide
2) Hit Edit button
3) Make a modification
4) Save
5) Navigate back to guide view by pressing Back (twice)
6) The guide is out of date

We could solve this in a few different ways:

1) Call `startActivityForResult` in guide view and have guide edit return true or false if the guide was or was not edited, respectively. This might be hard to determine and difficult to do.
2) Reload the guide in `onRestart` of guide view. We do the same thing for the user guides list.

**Comment by timothyasp** [comment]
I'm pretty sure we do this now.  Closing.
