### ISSUE TITLE
Scroll status carried across searches

### ISSUE THREAD

**Issue by xiongchiamiov** [iFixit/iFixitAndroid#167]
1. Open the iFixit app.
2. Search for `cover`.
3. Scroll down.
4. Search for `outlet`.
5. Observe that we are scrolled down in the search results, rather than viewing the top.

**Comment by xiongchiamiov** [comment]
:( my bugs

**Comment by davidrans** [comment]
@xiongchiamiov :(. We're closing and adding a "someday" label to issues that can't take priority for the foreseeable future. Hopefully, we'll get to at least some of them eventually.
