### ISSUE TITLE
Bitmap too large to be uploaded into a texture

### ISSUE THREAD

**Issue by marczych** [iFixit/iFixitAndroid#184]
W  01-13 16:49:24.640 | Bitmap too large to be uploaded into a texture (2412x1809, max=2048x2048)

I got hundreds of these errors when an image failed to load for a guide thumbnail. Anytime the menu drawer moved it logged it for every draw call. This was on a Galaxy Nexus.

My best guess is that the `no_image` resource doesn't have different versions for densities so it upscales it or something. http://stackoverflow.com/questions/10271020/bitmap-too-large-to-be-uploaded-into-a-texture

**Comment by timothyasp** [comment]
Is this still an assue @marczych
