### ISSUE TITLE
Not able to install application 

### ISSUE THREAD

**Issue by remyacv83** [iFixit/iFixitAndroid#255]
I am new to android development. I cloned the source code and followed the instrunctions in the Installation section. But when I build I get the following error:

Error:(132, 0) Could not find property 'dripassistKeyAlias' on 
SigningConfig_Decorated{name=dripassist, storeFile=C:\Users\remya\Documents\GitHub\iFixitAndroid\App\sites\dripassist\keystore, 
storePassword=null, keyAlias=null, keyPassword=null, storeType=C:\Users\remya\Documents\GitHub\iFixitAndroid\App\sites\dripassist\keystore}.

Can anyone help?

**Comment by marczych** [comment]
Sorry about that. I just followed the installation instructions on a fresh clone and it worked with my fix in #256. Let me know if you run into any other problems.

Thanks for the report!

**Comment by remyacv83** [comment]
Thanks a lot for the timely response...
I got it working!

**Comment by remyacv83** [comment]
Hi, I have a question..sorry I don't know if this is the right place to post..
I got a general idea about the model, ui and util folders and classes inside them. I could not find any SQLite/ MySQL database references. I could see JSON format, Arraylist populations etc. I also found the api folder. Is ifixit app connecting to an external server or website to pull data for the guide, gallery videos etc? Can you please explain about that and the corresponding classes in the source code?

**Comment by remyacv83** [comment]
Model folder is the SQLiteDB, arrayadapter is the controller here and view is equivalent to ui in this project..It is all new learning for me..
:)

**Comment by marczych** [comment]
You are correct - the app doesn't store much of anything on the device itself. All data is retrieved from the [iFixit API](https://www.ifixit.com/api/2.0/doc) and rendered natively in the app. The only exception to this is offline storage which downloads guides, images, and videos, stores them in a SQLite database, and uses _that_ as the data source when the device is offline.

The [api directory](https://github.com/iFixit/iFixitAndroid/tree/3985019758fcbff594b8d404e176e6a5a2e1c6d2/App/src/com/dozuki/ifixit/util/api) has all of the classes for interacting with the API (performing requests, defining endpoints, etc.). All of the images are displayed using [Picasso](http://square.github.io/picasso/) in the various views and controllers. The URLs for these come from the API.

I hope that this helps!

**Comment by remyacv83** [comment]
Thank you marchzych, you have been most helpful. Can you let me know if there is a Mobile Backend as Service (MBaS) involved here? Perhaps Google App Engine or others cloud storage like parse.com? I could not figure it out from the API code. 
Thanks in advance,
Remya

**Comment by marczych** [comment]
The backend is our production website (https://www.ifixit.com). For example, this is the endpoint that we request to display the [Xbox Red Ring of Death Fix Kit guide](https://www.ifixit.com/Guide/Xbox+360+Red+Ring+of+Death+Fix+Kit/3550): https://www.ifixit.com/api/2.0/guides/3550. We also have a private server for development that we use to test changes.

[This code](https://github.com/iFixit/iFixitAndroid/blob/3985019758fcbff594b8d404e176e6a5a2e1c6d2/App/src/com/dozuki/ifixit/util/api/ApiEndpoint.java#L848-L867) builds the URL for the given API call. You can also see some debug information in logcat if the app is built in debug mode.

> Thank you @marczych, you have been most helpful.

Happy to help!
