### ISSUE TITLE
Can't register new user: missing field: unqiue_username

### ISSUE THREAD

**Issue by addison-grant** [iFixit/iFixitAndroid#271]
From https://github.com/iFixit/iFixitAndroid/issues/266#issuecomment-288569541

*****

Creating an account through the app issues:
[img_2261](https://cloud.githubusercontent.com/assets/10889879/24224932/25312ddc-0f1b-11e7-8e55-4b2460f82151.jpg)

I'm guessing this is platform-independent, but this is a Samsung Galaxy S3, 4.4.2.

**Comment by timothyasp** [comment]
Fixed with an API update.
