### ISSUE TITLE
My Guides view: not always updating & seeing double

### ISSUE THREAD

**Issue by addison-grant** [iFixit/iFixitAndroid#273]
From https://github.com/iFixit/iFixitAndroid/issues/266#issuecomment-288575841

*****

For some reason My Guides isn't up to date even after pulling down to cause update

- [user contributions (desktop browser)](https://cloud.githubusercontent.com/assets/10889879/24225880/38d8f680-0f20-11e7-9257-76562c0edc9f.jpg)
- [guide is published](https://cloud.githubusercontent.com/assets/10889879/24225890/43e7a332-0f20-11e7-8402-eff1c50736a8.jpg)
- [1 my guides](https://cloud.githubusercontent.com/assets/10889879/24225894/4886dc8c-0f20-11e7-9d34-2f829069f2a4.jpg)

Samsung G S3, 4.4.2

**Comment by timothyasp** [comment]
This has been fixed.
