### ISSUE TITLE
Visible "Log In" link on internal browser doesn't integrate with app

### ISSUE THREAD

**Issue by cedmans** [iFixit/iFixitAndroid#46]
Between the initial app startup and going straight to a product Info page, there's no obvious login method in the app.

I tried logging in using the "Log In" link in the internal browser. (Because testing)

In landscape mode, the keyboard consistently covers needed textboxes for login info input. In portrait mode, it's only slightly better.

Once logged in, the app itself is unaware of that fact (such as after clicking the gallery button in the upper-right).

Repro:
1. Start app while not logged in
2. Visit a specific product info page
3. Observe the "Log In" link in the upper-right of the internal browser, and try to use it to log in.
4. Use the Gallery button in the upper-right of the app.

**Comment by timothyasp** [comment]
Wont fix.
